#!/usr/bin/env python3
"""Hybrid search for Rhizome's FAISS archives.

The script preserves the original command-line shape while adding:
- dense + SQLite FTS5 lexical retrieval with reciprocal-rank fusion;
- adaptive candidate expansion for sparse source/author filters;
- duplicate suppression and per-conversation/document diversity;
- optional neighbouring-chunk reconstruction;
- recency-aware reranking only when explicitly requested;
- structured provenance and retrieval diagnostics.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import pickle
import re
import sqlite3
import tempfile
from collections import defaultdict
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer


TOOL_VERSION = "2.0.0"
DEFAULT_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
RRF_K = 60
STOPWORDS = {
    "a", "about", "an", "and", "are", "as", "at", "be", "been", "but",
    "by", "did", "do", "does", "for", "from", "had", "has", "have", "he",
    "her", "his", "how", "i", "in", "is", "it", "its", "me", "my", "of",
    "on", "or", "our", "she", "so", "that", "the", "their", "them", "they",
    "this", "to", "was", "we", "were", "what", "when", "where", "which",
    "who", "why", "with", "you", "your",
}
RECENCY_TERMS = {
    "current", "latest", "last", "newest", "recent", "recently", "today",
    "tonight", "yesterday", "now", "most recent",
}

ARCHIVES = {
    "rhizomeml": {
        "path": Path(os.environ.get("RHIZOME_ARCHIVE_DIR", str(Path.home() / ".local/share/rhizome-stack/memory/archive"))),
        "index": "memory.index",
        "texts": "memory_texts.npy",
        "metadata": "memory_metadata.pkl",
        "lexical": "memory_lexical.sqlite3",
    },
    "books": {
        "path": Path(os.environ.get("BOOK_RAG_DIR", str(Path.home() / ".local/share/rhizome-stack/memory/books"))),
        "index": "rag.index",
        "texts": "rag_texts.npy",
        "metadata": "rag_metadata.pkl",
        "lexical": "rag_lexical.sqlite3",
    },
    "workspace": {
        "path": Path(os.environ.get("WORKSPACE_MEMORY_INDEX_DIR", str(Path.home() / ".local/share/rhizome-stack/memory/workspace"))),
        "index": "memory_notes.index",
        "texts": "memory_notes_texts.npy",
        "metadata": "memory_notes_metadata.pkl",
        "lexical": "memory_notes_lexical.sqlite3",
    },
}


def _jsonable(value: Any) -> Any:
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, np.generic):
        return value.item()
    return str(value)


def _clean_space(value: Any) -> str:
    return " ".join(str(value or "").split())


def _normalise(value: Any) -> str:
    text = _clean_space(value).casefold()
    return re.sub(r"[^\w]+", " ", text, flags=re.UNICODE).strip()


def _compact_text(value: Any, max_chars: int) -> str:
    text = _clean_space(value)
    if len(text) <= max_chars:
        return text
    cut = text[: max(1, max_chars - 1)].rsplit(" ", 1)[0]
    return (cut or text[: max_chars - 1]) + "…"


# Heuristic provenance classification. Cheap, no model call. The goal is to stop a
# snippet being attributed to a document's author just because it lives in that
# document (e.g. GPT-3 dialogue printed inside a Chalmers book). See guidance below.
_SPEAKER_LABEL = re.compile(r"(?:^|(?<=[.!?]\s))([A-Z][A-Z][A-Z .'-]{1,30}):\s")
_GENERATED_MARKERS = re.compile(
    r"\b(?:generated by|produced by|written by (?:an? )?(?:ai|language model|gpt|"
    r"chatbot)|gpt-?[234]|large language model|the model (?:wrote|produced|answered)|"
    r"cosplay(?:ing)?(?: as)?|"
    # "simulate/simulated ... <a speaker>" — provenance, not the topic of simulation.
    r"simulat\w*\s+(?:the\s+|a\s+)?(?:philosopher|author|speaker|persona|answers?|"
    r"responses?|voice|dialogue|as\s+[A-Z]))\b",
    re.IGNORECASE,
)
_QA_LABEL = re.compile(r"(?:^|\s)(?:Q|A)\s*:\s", re.MULTILINE)


# Tiered risk, not a binary. The job is not to understand the text; it is to make
# dangerous text expensive to trust. A false positive costs one extra context check;
# a false negative lets GPT-3 cosplaying as Chalmers become "Chalmers argues...".
# Dialogue is only ELEVATED (not high) because it can genuinely be the author's own
# speech — an interview, letter, or reproduced lecture — so resolve the speaker rather
# than assume it is never the author.
_RISK_BY_TYPE = {
    "narration": ("low", "Presumptively authorial; may attribute to the document author, subject to surrounding context."),
    "quotation": ("elevated", "Identify the quoted speaker/source before attributing to the author."),
    "dialogue": ("elevated", "Resolve the speaker before attributing; dialogue may still be the author (interview, letter, lecture)."),
    "generated_or_simulated": ("high", "Never attribute to the document author without explicit surrounding confirmation."),
    "unknown": ("low", "Too little text to classify; verify against context before attributing."),
}


def _classify_text_type(value: Any) -> dict[str, Any]:
    text = _clean_space(value)
    if not text:
        level, default = _RISK_BY_TYPE["unknown"]
        return {"text_type": "unknown", "attribution_risk": level, "default": default, "signals": []}
    signals: list[str] = []
    quote_chars = sum(text.count(c) for c in '"“”')
    quote_ratio = quote_chars / max(len(text), 1)
    if _GENERATED_MARKERS.search(text):
        signals.append("generated_or_simulated_marker")
    if _SPEAKER_LABEL.search(text) or _QA_LABEL.search(text):
        signals.append("speaker_label")
    if quote_chars >= 2 and quote_ratio > 0.004:
        signals.append("quotation_marks")
    if "generated_or_simulated_marker" in signals:
        text_type = "generated_or_simulated"
    elif "speaker_label" in signals:
        text_type = "dialogue"
    elif "quotation_marks" in signals:
        text_type = "quotation"
    else:
        text_type = "narration"
    level, default = _RISK_BY_TYPE[text_type]
    return {"text_type": text_type, "attribution_risk": level, "default": default, "signals": signals}


def _query_tokens(query: str) -> list[str]:
    raw = re.findall(r"[\w][\w'’-]*", query.casefold(), flags=re.UNICODE)
    useful = [token.strip("'’-") for token in raw]
    useful = [token for token in useful if len(token) >= 2 and token not in STOPWORDS]
    if not useful:
        useful = [token.strip("'’-") for token in raw if len(token.strip("'’-")) >= 2]
    seen: set[str] = set()
    return [token for token in useful if not (token in seen or seen.add(token))]


def _quoted_phrases(query: str) -> list[str]:
    return [_clean_space(item) for item in re.findall(r'["“](.+?)["”]', query) if _clean_space(item)]


def _fts_expression(query: str) -> str | None:
    phrases = _quoted_phrases(query)
    tokens = _query_tokens(query)[:24]
    parts: list[str] = []
    for phrase in phrases[:4]:
        parts.append(f'"{phrase.replace(chr(34), chr(34) * 2)}"')
    for token in tokens:
        parts.append(f'"{token.replace(chr(34), chr(34) * 2)}"')
    return " OR ".join(dict.fromkeys(parts)) or None


def _parse_datetime(value: Any) -> datetime | None:
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        dt = value
    elif isinstance(value, date):
        dt = datetime(value.year, value.month, value.day)
    elif isinstance(value, (int, float, np.integer, np.floating)):
        number = float(value)
        if number > 10_000_000_000:
            number /= 1000.0
        try:
            return datetime.fromtimestamp(number, tz=timezone.utc)
        except (OverflowError, OSError, ValueError):
            return None
    else:
        text = str(value).strip()
        if not text:
            return None
        if re.fullmatch(r"\d+(?:\.\d+)?", text):
            return _parse_datetime(float(text))
        text = text.replace("Z", "+00:00")
        try:
            dt = datetime.fromisoformat(text)
        except ValueError:
            for pattern in ("%Y-%m-%d", "%d %B %Y", "%d %b %Y"):
                try:
                    dt = datetime.strptime(text, pattern)
                    break
                except ValueError:
                    continue
            else:
                return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def _metadata_datetime(meta: dict[str, Any]) -> datetime | None:
    for key in ("timestamp", "datetime_utc", "date", "source_modified_at", "updated_at"):
        parsed = _parse_datetime(meta.get(key))
        if parsed:
            return parsed
    return None


def _looks_recent_query(query: str) -> bool:
    q = _normalise(query)
    tokens = set(q.split())
    return "most recent" in q or any(
        term in tokens for term in RECENCY_TERMS if " " not in term
    )


def _archive_paths(archive: str) -> dict[str, Path]:
    config = ARCHIVES[archive]
    root_override = os.environ.get(f"RHIZOME_{archive.upper()}_PATH")
    root = Path(root_override).expanduser() if root_override else config["path"]
    return {
        "root": root,
        "index": root / config["index"],
        "texts": root / config["texts"],
        "metadata": root / config["metadata"],
        "lexical": root / config["lexical"],
        "manifest": root / "manifest.json",
    }


def _manifest_model(paths: dict[str, Path]) -> str | None:
    try:
        payload = json.loads(paths["manifest"].read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return None
    for key in ("model", "embedding_model", "model_name"):
        value = payload.get(key)
        if value:
            return str(value)
    archive_info = payload.get("archive")
    if isinstance(archive_info, dict) and archive_info.get("model"):
        return str(archive_info["model"])
    config = payload.get("config")
    if isinstance(config, dict) and config.get("model"):
        return str(config["model"])
    return None


def _load_archive(archive: str) -> tuple[dict[str, Path], Any, np.ndarray, list[dict[str, Any]]]:
    paths = _archive_paths(archive)
    for key in ("index", "texts", "metadata"):
        if not paths[key].exists():
            raise FileNotFoundError(paths[key])

    index = faiss.read_index(str(paths["index"]))
    texts = np.load(paths["texts"], allow_pickle=True)
    with paths["metadata"].open("rb") as handle:
        metadata_raw = pickle.load(handle)
    metadata = [dict(item or {}) for item in metadata_raw]

    if index.ntotal != len(texts) or index.ntotal != len(metadata):
        raise RuntimeError(
            "archive count mismatch: "
            f"index={index.ntotal}, texts={len(texts)}, metadata={len(metadata)}"
        )
    return paths, index, texts, metadata


def _source_name(meta: dict[str, Any], archive: str) -> str:
    if archive == "workspace":
        return str(meta.get("source_kind") or meta.get("source") or "note")
    return str(meta.get("source") or ("book" if archive == "books" else "conversation"))


def _memory_uri(meta: dict[str, Any], index: int, archive: str) -> str:
    if archive == "workspace":
        source_path = quote(str(meta.get("source_path") or "memory"), safe="/._-")
        line_start = meta.get("line_start") or 1
        line_end = meta.get("line_end") or line_start
        return f"memory://{source_path}#L{line_start}-L{line_end}"
    if archive == "books":
        source = quote(str(meta.get("source") or meta.get("filename") or "book"), safe="/._-")
        word_offset = meta.get("word_offset", index)
        return f"bookrag://{source}#word-{word_offset}"

    source = str(meta.get("source") or "conversation")
    if source == "pdf":
        document_id = quote(str(meta.get("document_id") or "unknown"), safe="._-")
        chunk_id = meta.get("chunk_id", 0)
        return f"rhizome://pdf/{document_id}#chunk-{chunk_id}"
    conversation_id = quote(str(meta.get("conversation_id") or "unknown"), safe="._-")
    message_id = quote(str(meta.get("message_id", index)), safe="._-")
    chunk_id = meta.get("chunk_id", 0)
    return f"rhizome://conversation/{conversation_id}/{message_id}#chunk-{chunk_id}"


def _parent_key(meta: dict[str, Any], archive: str, index: int) -> tuple[Any, ...]:
    if archive == "workspace":
        return ("workspace", meta.get("source_path") or index, meta.get("heading_path") or meta.get("heading"))
    if archive == "books":
        return ("book", meta.get("source") or meta.get("filename") or index)
    if meta.get("source") == "pdf":
        return ("pdf", meta.get("document_id") or meta.get("filename") or index)
    return ("conversation", meta.get("conversation_id") or index)


def _context_group_key(meta: dict[str, Any], archive: str) -> tuple[Any, ...] | None:
    if archive == "workspace":
        return ("workspace", meta.get("source_path"), meta.get("heading_path") or meta.get("heading"))
    if archive == "books":
        return ("book", meta.get("source") or meta.get("filename"))
    if meta.get("source") == "pdf":
        return ("pdf", meta.get("document_id") or meta.get("filename"))
    if meta.get("conversation_id") is not None:
        return ("message", meta.get("conversation_id"), meta.get("message_id"))
    return None


def _context_position(meta: dict[str, Any], archive: str, fallback: int) -> float:
    if archive == "workspace":
        return float(meta.get("line_start") or fallback)
    if archive == "books":
        return float(meta.get("word_offset") or fallback)
    return float(meta.get("chunk_id") if meta.get("chunk_id") is not None else fallback)


def _lexical_manifest(paths: dict[str, Path], count: int) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "entry_count": int(count),
        "texts_mtime_ns": paths["texts"].stat().st_mtime_ns,
        "metadata_mtime_ns": paths["metadata"].stat().st_mtime_ns,
    }


def _read_lexical_manifest(db_path: Path) -> dict[str, Any] | None:
    if not db_path.exists():
        return None
    try:
        with sqlite3.connect(db_path) as connection:
            rows = connection.execute("SELECT key, value FROM manifest").fetchall()
        return {key: json.loads(value) for key, value in rows}
    except (sqlite3.Error, ValueError, OSError):
        return None


def _lexical_status(paths: dict[str, Path], count: int) -> tuple[bool, str]:
    manifest = _read_lexical_manifest(paths["lexical"])
    if not manifest:
        return False, "missing"
    expected = _lexical_manifest(paths, count)
    if any(manifest.get(key) != value for key, value in expected.items()):
        return False, "stale"
    return True, "ready"


def _build_lexical_sidecar(
    paths: dict[str, Path],
    texts: np.ndarray,
    metadata: list[dict[str, Any]],
    archive: str,
) -> dict[str, Any]:
    paths["root"].mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=paths["lexical"].name + ".",
        suffix=".tmp",
        dir=paths["root"],
    )
    os.close(fd)
    temporary = Path(temporary_name)
    try:
        with sqlite3.connect(temporary) as connection:
            connection.execute("PRAGMA journal_mode=OFF")
            connection.execute("PRAGMA synchronous=OFF")
            connection.execute("PRAGMA temp_store=MEMORY")
            connection.execute(
                "CREATE VIRTUAL TABLE chunks USING fts5("
                "text, source UNINDEXED, author UNINDEXED, conversation_id UNINDEXED, "
                "document_id UNINDEXED, filename UNINDEXED, tokenize='unicode61 remove_diacritics 2'"
                ")"
            )
            batch = []
            for index, (text, meta) in enumerate(zip(texts, metadata)):
                batch.append(
                    (
                        index,
                        str(text),
                        _source_name(meta, archive),
                        str(meta.get("author") or ""),
                        str(meta.get("conversation_id") or ""),
                        str(meta.get("document_id") or ""),
                        str(meta.get("filename") or meta.get("source_path") or ""),
                    )
                )
                if len(batch) >= 2000:
                    connection.executemany(
                        "INSERT INTO chunks(rowid, text, source, author, conversation_id, document_id, filename) "
                        "VALUES (?, ?, ?, ?, ?, ?, ?)",
                        batch,
                    )
                    batch.clear()
            if batch:
                connection.executemany(
                    "INSERT INTO chunks(rowid, text, source, author, conversation_id, document_id, filename) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?)",
                    batch,
                )
            connection.execute("CREATE TABLE manifest(key TEXT PRIMARY KEY, value TEXT NOT NULL)")
            connection.executemany(
                "INSERT INTO manifest(key, value) VALUES (?, ?)",
                [(key, json.dumps(value)) for key, value in _lexical_manifest(paths, len(texts)).items()],
            )
            connection.commit()
        os.replace(temporary, paths["lexical"])
    finally:
        temporary.unlink(missing_ok=True)
    return {"ok": True, "path": str(paths["lexical"]), "entries": len(texts)}


def _passes_filters(
    meta: dict[str, Any],
    archive: str,
    source: str,
    author: str,
    conversation_id: str | None,
    since: datetime | None,
    until: datetime | None,
) -> bool:
    if source != "all" and _source_name(meta, archive).casefold() != source.casefold():
        return False
    if author != "all" and str(meta.get("author") or "").casefold() != author.casefold():
        return False
    if conversation_id and str(meta.get("conversation_id") or "") != conversation_id:
        return False
    dt = _metadata_datetime(meta)
    if since and (not dt or dt < since):
        return False
    if until and (not dt or dt > until):
        return False
    return True


def _dense_candidates(
    index: Any,
    vector: np.ndarray,
    metadata: list[dict[str, Any]],
    archive: str,
    args: argparse.Namespace,
) -> tuple[dict[int, float], dict[int, int], int]:
    if index.ntotal == 0:
        return {}, {}, 0
    target = max(args.k * max(args.max_per_parent, 1) * 6, args.k)
    candidate_k = min(index.ntotal, max(128, args.k * 24))
    max_candidate_k = index.ntotal if any(
        (args.source != "all", args.author != "all", args.conversation_id, args.since, args.until)
    ) else min(index.ntotal, max(4096, args.k * 100))

    accepted: list[tuple[float, int]] = []
    while True:
        scores, ids = index.search(vector, candidate_k)
        accepted = []
        for score, idx in zip(scores[0].tolist(), ids[0].tolist()):
            if idx < 0:
                continue
            if _passes_filters(
                metadata[idx], archive, args.source, args.author,
                args.conversation_id, args.since_dt, args.until_dt,
            ):
                accepted.append((float(score), int(idx)))
        if len(accepted) >= target or candidate_k >= max_candidate_k:
            break
        candidate_k = min(max_candidate_k, candidate_k * 2)

    dense_scores = {idx: score for score, idx in accepted}
    dense_ranks = {idx: rank for rank, (_, idx) in enumerate(accepted, start=1)}
    return dense_scores, dense_ranks, candidate_k


def _lexical_candidates(
    db_path: Path,
    query: str,
    metadata: list[dict[str, Any]],
    archive: str,
    args: argparse.Namespace,
) -> tuple[dict[int, int], int]:
    expression = _fts_expression(query)
    if not expression:
        return {}, 0
    fetch_limit = min(len(metadata), max(128, args.k * 30))
    try:
        with sqlite3.connect(db_path) as connection:
            rows = connection.execute(
                "SELECT rowid, bm25(chunks) AS lexical_score "
                "FROM chunks WHERE chunks MATCH ? ORDER BY lexical_score LIMIT ?",
                (expression, fetch_limit),
            ).fetchall()
    except sqlite3.Error:
        return {}, 0

    ranks: dict[int, int] = {}
    for idx, _score in rows:
        idx = int(idx)
        if idx < 0 or idx >= len(metadata):
            continue
        if not _passes_filters(
            metadata[idx], archive, args.source, args.author,
            args.conversation_id, args.since_dt, args.until_dt,
        ):
            continue
        ranks[idx] = len(ranks) + 1
    return ranks, len(rows)


def _token_coverage(query_tokens: list[str], text: str) -> float:
    if not query_tokens:
        return 0.0
    haystack = _normalise(text)
    found = sum(1 for token in query_tokens if re.search(rf"\b{re.escape(token)}\b", haystack))
    return found / len(query_tokens)


def _exact_phrase_match(query: str, text: str) -> bool:
    haystack = _normalise(text)
    phrases = _quoted_phrases(query)
    if not phrases:
        normalized_query = _normalise(query)
        if 2 <= len(normalized_query.split()) <= 12:
            phrases = [normalized_query]
    return any(_normalise(phrase) in haystack for phrase in phrases if _normalise(phrase))


def _age_days(meta: dict[str, Any]) -> float | None:
    dt = _metadata_datetime(meta)
    if not dt:
        return None
    return max(0.0, (datetime.now(timezone.utc) - dt).total_seconds() / 86400.0)


def _candidate_score(
    idx: int,
    query: str,
    text: str,
    meta: dict[str, Any],
    dense_scores: dict[int, float],
    dense_ranks: dict[int, int],
    lexical_ranks: dict[int, int],
    prefer_recent: bool,
) -> dict[str, Any]:
    dense_rank = dense_ranks.get(idx)
    lexical_rank = lexical_ranks.get(idx)
    dense_score = dense_scores.get(idx)
    query_tokens = _query_tokens(query)
    coverage = _token_coverage(query_tokens, text)
    exact = _exact_phrase_match(query, text)

    combined = 0.0
    if dense_rank:
        combined += 1.0 / (RRF_K + dense_rank)
    if lexical_rank:
        combined += 1.15 / (RRF_K + lexical_rank)
    if dense_score is not None and math.isfinite(dense_score):
        combined += max(0.0, min(1.0, dense_score)) * 0.012
    combined += coverage * 0.012
    if exact:
        combined += 0.028
    age = _age_days(meta)
    if prefer_recent and age is not None:
        combined += 0.012 / (1.0 + age / 365.0)

    if exact or (dense_rank is not None and lexical_rank is not None and min(dense_rank, lexical_rank) <= 50):
        confidence = "strong"
    elif lexical_rank is not None or (dense_score is not None and dense_score >= 0.30):
        confidence = "medium"
    else:
        confidence = "weak"

    return {
        "combined_score": combined,
        "dense_score": dense_score,
        "dense_rank": dense_rank,
        "lexical_rank": lexical_rank,
        "token_coverage": coverage,
        "exact_phrase_match": exact,
        "age_days": age,
        "confidence": confidence,
    }


def _dedupe_and_diversify(
    ranked: list[tuple[int, dict[str, Any]]],
    texts: np.ndarray,
    metadata: list[dict[str, Any]],
    archive: str,
    k: int,
    max_per_parent: int,
) -> list[tuple[int, dict[str, Any]]]:
    selected: list[tuple[int, dict[str, Any]]] = []
    seen_text: set[str] = set()
    parent_counts: dict[tuple[Any, ...], int] = defaultdict(int)
    for idx, scoring in ranked:
        fingerprint = hashlib.sha1(_normalise(texts[idx]).encode("utf-8")).hexdigest()
        if fingerprint in seen_text:
            continue
        parent = _parent_key(metadata[idx], archive, idx)
        if parent_counts[parent] >= max_per_parent:
            continue
        seen_text.add(fingerprint)
        parent_counts[parent] += 1
        selected.append((idx, scoring))
        if len(selected) >= k:
            break
    return selected


def _context_lookup(
    selected_ids: Iterable[int],
    texts: np.ndarray,
    metadata: list[dict[str, Any]],
    archive: str,
    context_chunks: int,
    snippet_chars: int,
) -> dict[int, dict[str, list[dict[str, Any]]]]:
    if context_chunks <= 0:
        return {}
    wanted_groups = {
        key for idx in selected_ids
        if (key := _context_group_key(metadata[idx], archive)) is not None
    }
    groups: dict[tuple[Any, ...], list[int]] = defaultdict(list)
    for idx, meta in enumerate(metadata):
        key = _context_group_key(meta, archive)
        if key in wanted_groups:
            groups[key].append(idx)
    for key, ids in groups.items():
        ids.sort(key=lambda item: _context_position(metadata[item], archive, item))

    result: dict[int, dict[str, list[dict[str, Any]]]] = {}
    for idx in selected_ids:
        key = _context_group_key(metadata[idx], archive)
        ids = groups.get(key or (), [])
        if idx not in ids:
            continue
        position = ids.index(idx)
        before_ids = ids[max(0, position - context_chunks):position]
        after_ids = ids[position + 1: position + 1 + context_chunks]

        def pack(neighbour: int) -> dict[str, Any]:
            return {
                "uri": _memory_uri(metadata[neighbour], neighbour, archive),
                "snippet": _compact_text(texts[neighbour], min(snippet_chars, 700)),
            }

        result[idx] = {
            "before": [pack(item) for item in before_ids],
            "after": [pack(item) for item in after_ids],
        }
    return result


def _public_metadata(meta: dict[str, Any], archive: str) -> dict[str, Any]:
    keys = (
        "source", "source_kind", "source_path", "heading", "heading_path", "date",
        "author", "timestamp", "datetime_utc", "filename", "word_offset",
        "book", "source_file", "page_start", "page_end",
        "segment_start_page", "segment_end_page", "embedding_model",
        "conversation_id", "message_id", "chunk_id", "total_chunks", "document_id",
        "line_start", "line_end", "char_count", "token_estimate", "source_modified_at",
    )
    output = {key: _jsonable(meta.get(key)) for key in keys if meta.get(key) is not None}
    output["source"] = _source_name(meta, archive)
    return output


def query_archive(args: argparse.Namespace) -> dict[str, Any]:
    paths, index, texts, metadata = _load_archive(args.archive)

    lexical_ready, lexical_state = _lexical_status(paths, len(texts))
    lexical_build = None
    if args.rebuild_lexical or (args.build_lexical and not lexical_ready):
        lexical_build = _build_lexical_sidecar(paths, texts, metadata, args.archive)
        lexical_ready, lexical_state = _lexical_status(paths, len(texts))

    if args.build_lexical_only:
        if not lexical_ready:
            lexical_build = _build_lexical_sidecar(paths, texts, metadata, args.archive)
            lexical_ready, lexical_state = _lexical_status(paths, len(texts))
        return {
            "ok": lexical_ready,
            "tool_version": TOOL_VERSION,
            "archive": args.archive,
            "lexical_sidecar": {
                "state": lexical_state,
                "path": str(paths["lexical"]),
                "build": lexical_build,
            },
        }

    if not args.query or not args.query.strip():
        raise ValueError("query must not be empty")

    model_name = args.model
    if model_name == "auto":
        model_name = _manifest_model(paths) or DEFAULT_MODEL
    model = SentenceTransformer(model_name, device=args.device)
    vector = model.encode([args.query], normalize_embeddings=True).astype("float32")
    if vector.ndim != 2 or vector.shape[0] != 1:
        raise RuntimeError(f"embedding model returned unexpected shape {vector.shape}")
    if vector.shape[1] != index.d:
        raise RuntimeError(
            f"embedding dimension mismatch: query model={vector.shape[1]}, archive={index.d}. "
            "Use the same model that built the archive."
        )

    dense_scores, dense_ranks, dense_examined = _dense_candidates(
        index, vector, metadata, args.archive, args
    )
    lexical_ranks: dict[int, int] = {}
    lexical_examined = 0
    if args.lexical != "off" and lexical_ready:
        lexical_ranks, lexical_examined = _lexical_candidates(
            paths["lexical"], args.query, metadata, args.archive, args
        )
    elif args.lexical == "on" and not lexical_ready:
        raise RuntimeError(
            f"lexical sidecar is {lexical_state}; rebuild it with --build-lexical-only"
        )

    candidate_ids = set(dense_ranks) | set(lexical_ranks)
    prefer_recent = bool(args.prefer_recent or _looks_recent_query(args.query))
    ranked: list[tuple[int, dict[str, Any]]] = []
    for idx in candidate_ids:
        scoring = _candidate_score(
            idx,
            args.query,
            str(texts[idx]),
            metadata[idx],
            dense_scores,
            dense_ranks,
            lexical_ranks,
            prefer_recent,
        )
        ranked.append((idx, scoring))
    ranked.sort(key=lambda item: item[1]["combined_score"], reverse=True)
    selected = _dedupe_and_diversify(
        ranked, texts, metadata, args.archive, args.k, args.max_per_parent
    )
    contexts = _context_lookup(
        [idx for idx, _ in selected],
        texts,
        metadata,
        args.archive,
        args.context_chunks,
        args.snippet_chars,
    )

    results = []
    for rank, (idx, scoring) in enumerate(selected, start=1):
        result = {
            "rank": rank,
            "score": round(scoring["combined_score"], 8),
            "confidence": scoring["confidence"],
            "uri": _memory_uri(metadata[idx], idx, args.archive),
            "snippet": _compact_text(texts[idx], args.snippet_chars),
            "metadata": _public_metadata(metadata[idx], args.archive),
            "match": {
                "dense_score": None if scoring["dense_score"] is None else round(float(scoring["dense_score"]), 6),
                "dense_rank": scoring["dense_rank"],
                "lexical_rank": scoring["lexical_rank"],
                "token_coverage": round(float(scoring["token_coverage"]), 3),
                "exact_phrase": bool(scoring["exact_phrase_match"]),
                "age_days": None if scoring["age_days"] is None else round(float(scoring["age_days"]), 1),
            },
        }
        result["provenance"] = _classify_text_type(texts[idx])
        if idx in contexts:
            result["adjacent_context"] = contexts[idx]
        results.append(result)

    warnings = []
    if args.lexical != "off" and not lexical_ready:
        warnings.append(
            f"Lexical sidecar is {lexical_state}; retrieval used dense vectors only. "
            f"Build it once with: {Path(__file__).name} --archive {args.archive} --build-lexical-only"
        )
    if len(results) < args.k:
        warnings.append(
            f"Only {len(results)} distinct results survived filters and diversity limits out of {args.k} requested."
        )

    mode = "hybrid" if lexical_ranks else "dense"
    attribution_flagged = [
        r["rank"] for r in results
        if r.get("provenance", {}).get("attribution_risk") in ("elevated", "high")
    ]
    guidance = (
        "A result proves that this text exists in local memory; it does not independently prove "
        "that every factual claim inside the remembered text is true. Prefer strong hybrid/exact "
        "matches, use adjacent_context to reconstruct meaning, and surface conflicts between old "
        "and newer memories rather than silently choosing one. "
        "ATTRIBUTION RULE: never attribute a statement to a document's author (or to a person) "
        "solely because it appears in that document. Check each result's provenance.text_type and "
        "provenance.attribution_risk first. Treat narration as presumptively authorial (may attribute, "
        "subject to context). Quotation and dialogue are ELEVATED risk — identify/resolve the quoted "
        "speaker before attributing (dialogue can still be the author, e.g. an interview or letter). "
        "generated_or_simulated is HIGH risk — never attribute to the document author without explicit "
        "surrounding confirmation. For any strong attribution ('X argues Y'), verify it still holds "
        "after expanding adjacent_context before asserting it; a hit must survive context expansion to "
        "become an attributed claim."
    )
    if attribution_flagged:
        guidance += (
            f" WARNING: results at ranks {attribution_flagged} are elevated/high attribution risk "
            "(quotation/dialogue/generated) — resolve the speaker/source against surrounding context "
            "before attributing them to the document's author."
        )
    return {
        "ok": True,
        "tool_version": TOOL_VERSION,
        "query": args.query,
        "count": len(results),
        "archive": {
            "name": args.archive,
            "entries": int(index.ntotal),
            "dimensions": int(index.d),
            "model": model_name,
        },
        "retrieval": {
            "mode": mode,
            "prefer_recent": prefer_recent,
            "dense_candidates_examined": dense_examined,
            "lexical_candidates_examined": lexical_examined,
            "lexical_sidecar": lexical_state,
            "context_chunks": args.context_chunks,
            "max_per_parent": args.max_per_parent,
            "filters": {
                "source": args.source,
                "author": args.author,
                "conversation_id": args.conversation_id,
                "since": args.since,
                "until": args.until,
            },
        },
        "guidance": guidance,
        "warnings": warnings,
        "results": results,
    }


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Hybrid search of local Rhizome FAISS archives.")
    parser.add_argument("query", nargs="?", help="Natural-language or exact-phrase query.")
    parser.add_argument("--archive", choices=sorted(ARCHIVES), default="rhizomeml")
    parser.add_argument("-k", type=int, default=5)
    parser.add_argument("--snippet-chars", type=int, default=900)
    parser.add_argument("--source", default="all", help="Exact source/source_kind filter, or all.")
    parser.add_argument("--author", default="all", help="Exact author filter, or all.")
    parser.add_argument("--conversation-id")
    parser.add_argument("--since", help="ISO date/datetime; excludes undated records.")
    parser.add_argument("--until", help="ISO date/datetime; excludes undated records.")
    parser.add_argument("--prefer-recent", action="store_true")
    parser.add_argument("--context-chunks", type=int, default=1)
    parser.add_argument("--max-per-parent", type=int, default=2)
    parser.add_argument("--lexical", choices=("auto", "on", "off"), default="auto")
    parser.add_argument("--build-lexical", action="store_true", help="Build the sidecar if missing/stale, then query.")
    parser.add_argument("--rebuild-lexical", action="store_true")
    parser.add_argument("--build-lexical-only", action="store_true")
    parser.add_argument("--model", default="auto")
    parser.add_argument("--device", default="cpu")
    return parser


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()
    args.k = max(1, min(int(args.k or 5), 20))
    args.snippet_chars = max(160, min(int(args.snippet_chars or 900), 4000))
    args.context_chunks = max(0, min(int(args.context_chunks or 0), 3))
    args.max_per_parent = max(1, min(int(args.max_per_parent or 2), 6))
    try:
        args.since_dt = _parse_datetime(args.since)
        args.until_dt = _parse_datetime(args.until)
        if args.since and not args.since_dt:
            raise ValueError(f"invalid --since value: {args.since}")
        if args.until and not args.until_dt:
            raise ValueError(f"invalid --until value: {args.until}")
        if args.since_dt and args.until_dt and args.since_dt > args.until_dt:
            raise ValueError("--since must be earlier than or equal to --until")
        payload = query_archive(args)
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    except Exception as exc:
        print(
            json.dumps(
                {
                    "ok": False,
                    "tool_version": TOOL_VERSION,
                    "archive": getattr(args, "archive", None),
                    "query": getattr(args, "query", None),
                    "error": type(exc).__name__,
                    "detail": str(exc),
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        raise SystemExit(1)


if __name__ == "__main__":
    main()
